### ISSUE TITLE
An extra step to make Github Actions works

### ISSUE THREAD

**Issue by monolithstd** [finsweet/developer-starter#31]
I noticed a “new step” to start with DS and it seems that you haven’t talk about it anywhere.
So I thought it might interest you.

When I clone your DS Template on my GitHub, I add the NPM token in Actions. Easy.
If we only do this, we will have an error when pushing to NPM. GitHub Actions is not permitted to create or approve pull requests.
![Capture d’écran 2023-03-02 à 16 26 18](https://user-images.githubusercontent.com/98360019/223204421-1f444ad2-3a09-4638-bd8e-97e91c0745e8.png)

In order to make it work, we need to go to Repo Settings/Actions/General/Workflow Permissions and check “Read and write permissions” and “Allow Github Actions to create and approve pull requests”

Before (by default): 
![Capture d’écran 2023-03-02 à 16 25 55](https://user-images.githubusercontent.com/98360019/223204576-f41ded4f-7615-4954-b45b-3c08e9f6ba15.png)

After:
![Capture d’écran 2023-03-02 à 16 25 50](https://user-images.githubusercontent.com/98360019/223204623-3b5e0d36-739f-40f7-bf26-fba3e77fce1a.png)

Then the Action work perfectly !
![Capture d’écran 2023-03-02 à 16 27 02](https://user-images.githubusercontent.com/98360019/223204680-9f66561a-1fee-4720-bd02-777dba2f1742.png)

There is no documentation about this extra step so I thought it was useful to submit a new issue.
That's it ! 

Trully love your work !
Have a great day !

**Comment by alexiglesias93** [comment]
Great suggestion, addressed in #34 , thank you!
