### ISSUE TITLE
Build fails with GSAP

### ISSUE THREAD

**Issue by samsostudios** [finsweet/developer-starter#38]
I am getting a failed build when using the dev starter and installing GSAP. First I created a copy of this starter, ran 'pnpm add gsap', imported gsap to index.ts and initialized a timeline. When I run 'pnpm build' the build file is populated with looks like and error (see screenshot).

<img width="1214" alt="Screenshot 2023-03-09 at 8 49 26 PM" src="https://user-images.githubusercontent.com/22227806/224346853-3b105549-c976-4292-ac18-dab21c67341b.png">

I am assuming this is something the to do with build.js file? 

Anyone have ideas here?

**Comment by samsostudios** [comment]
@alexiglesias93 https://github.com/samsostudios/fs-2

**Comment by samsostudios** [comment]
@alexiglesias93 Were you able to reproduce?

**Comment by alexiglesias93** [comment]
@samsostudios I see you closed the issue, is that because you manage to solve it?
